// Code generated by scripts/generate-config-constants.go. DO NOT EDIT.

package config

// Configuration key constants - automatically generated from registry
// These constants provide compile-time safety when referencing config keys
const (
	KeyAppLogLevel                      = "app.log_level"                       // Logging level for the application (trace, debug, info, warn, error, fatal, pa...
	KeyAppLogConsoleLevel               = "app.log.console_level"               // Console log level (trace, debug, info, warn, error, fatal, panic). If empty, ...
	KeyAppLogFileEnabled                = "app.log.file_enabled"                // Enable file logging to capture detailed logs
	KeyAppLogFilePath                   = "app.log.file_path"                   // Path to the log file (created with secure 0600 permissions)
	KeyAppLogFileLevel                  = "app.log.file_level"                  // File log level (trace, debug, info, warn, error, fatal, panic)
	KeyAppLogColorEnabled               = "app.log.color_enabled"               // Enable colored console output (auto, true, false). Auto detects TTY.
	KeyAppLogFileMaxSize                = "app.log.file_max_size"               // Maximum size in megabytes before log file is rotated
	KeyAppLogFileMaxBackups             = "app.log.file_max_backups"            // Maximum number of old log files to retain
	KeyAppLogFileMaxAge                 = "app.log.file_max_age"                // Maximum number of days to retain old log files
	KeyAppLogFileCompress               = "app.log.file_compress"               // Compress rotated log files with gzip
	KeyAppLogSamplingEnabled            = "app.log.sampling_enabled"            // Enable log sampling for high-volume scenarios
	KeyAppLogSamplingInitial            = "app.log.sampling_initial"            // Number of messages to log per second before sampling
	KeyAppLogSamplingThereafter         = "app.log.sampling_thereafter"         // Number of messages to log thereafter per second
	KeyAppDocsOutputFormat              = "app.docs.output_format"              // Output format for documentation (markdown, yaml)
	KeyAppDocsOutputFile                = "app.docs.output_file"                // Output file for documentation (defaults to stdout)
	KeyAppApplyVault                    = "app.apply.vault"                     // Path to vault root
	KeyAppApplyJson                     = "app.apply.json"                      // Output in JSON format
	KeyAppApplyDryRun                   = "app.apply.dry_run"                   // Preview without executing
	KeyAppApplyDiff                     = "app.apply.diff"                      // Show unified diffs
	KeyAppApplyCommit                   = "app.apply.commit"                    // Stage and commit all changes
	KeyAppCheckFailFast                 = "app.check.fail_fast"                 // Stop on first failed check
	KeyAppCheckVerbose                  = "app.check.verbose"                   // Show verbose output including command details
	KeyAppCheckParallel                 = "app.check.parallel"                  // Run checks within each category in parallel (disable with --parallel=false)
	KeyAppCheckCategory                 = "app.check.category"                  // Filter to specific categories (comma-separated: environment,quality,architect...
	KeyAppCheckTiming                   = "app.check.timing"                    // Show duration for each check in the output
	KeyAppDataviewrenderVault           = "app.dataviewrender.vault"            // Path to vault root
	KeyAppDataviewrenderJson            = "app.dataviewrender.json"             // Output in JSON format
	KeyAppDataviewrenderDryRun          = "app.dataviewrender.dry_run"          // Preview without writing
	KeyAppDataviewrenderDiff            = "app.dataviewrender.diff"             // Show unified diff
	KeyAppDataviewrenderCommit          = "app.dataviewrender.commit"           // Stage and commit
	KeyAppDataviewrenderForce           = "app.dataviewrender.force"            // Override checksum mismatch
	KeyAppDataviewrenderSectionKey      = "app.dataviewrender.section_key"      // Section key to render
	KeyAppDataviewlintVault             = "app.dataviewlint.vault"              // Path to vault root
	KeyAppDataviewlintJson              = "app.dataviewlint.json"               // Output in JSON format
	KeyAppDoctorVault                   = "app.doctor.vault"                    // Path to vault root
	KeyAppDoctorJson                    = "app.doctor.json"                     // Output in JSON format
	KeyAppFrontmatterVault              = "app.frontmatter.vault"               // Path to vault root
	KeyAppFrontmatterJson               = "app.frontmatter.json"                // Output in JSON format
	KeyAppFrontmattersetVault           = "app.frontmatterset.vault"            // Path to vault root
	KeyAppFrontmattersetJson            = "app.frontmatterset.json"             // Output in JSON format
	KeyAppFrontmattersetDryRun          = "app.frontmatterset.dry_run"          // Preview changes without writing
	KeyAppFrontmattersetDiff            = "app.frontmatterset.diff"             // Show unified diff
	KeyAppFrontmattersetCommit          = "app.frontmatterset.commit"           // Stage and commit after mutation
	KeyAppFrontmattersetAllowExtra      = "app.frontmatterset.allow_extra"      // Allow keys not in type schema
	KeyAppFrontmatterunsetVault         = "app.frontmatterunset.vault"          // Path to vault root
	KeyAppFrontmatterunsetJson          = "app.frontmatterunset.json"           // Output in JSON format
	KeyAppFrontmatterunsetDryRun        = "app.frontmatterunset.dry_run"        // Preview changes without writing
	KeyAppFrontmatterunsetDiff          = "app.frontmatterunset.diff"           // Show unified diff
	KeyAppFrontmatterunsetCommit        = "app.frontmatterunset.commit"         // Stage and commit after mutation
	KeyAppFrontmattermergeVault         = "app.frontmattermerge.vault"          // Path to vault root
	KeyAppFrontmattermergeJson          = "app.frontmattermerge.json"           // Output in JSON format
	KeyAppFrontmattermergeDryRun        = "app.frontmattermerge.dry_run"        // Preview changes without writing
	KeyAppFrontmattermergeDiff          = "app.frontmattermerge.diff"           // Show unified diff
	KeyAppFrontmattermergeCommit        = "app.frontmattermerge.commit"         // Stage and commit after mutation
	KeyAppFrontmattermergeAllowExtra    = "app.frontmattermerge.allow_extra"    // Allow keys not in type schema
	KeyAppFrontmattermergeFile          = "app.frontmattermerge.file"           // YAML file with fields to merge
	KeyAppFrontmatternormalizeVault     = "app.frontmatternormalize.vault"      // Path to vault root
	KeyAppFrontmatternormalizeJson      = "app.frontmatternormalize.json"       // Output in JSON format
	KeyAppFrontmatternormalizeDryRun    = "app.frontmatternormalize.dry_run"    // Preview changes without writing
	KeyAppFrontmatternormalizeDiff      = "app.frontmatternormalize.diff"       // Show unified diff
	KeyAppFrontmatternormalizeCommit    = "app.frontmatternormalize.commit"     // Stage and commit after mutation
	KeyAppFrontmatternormalizeStripTime = "app.frontmatternormalize.strip_time" // Force all datetimes to date-only
	KeyAppGitstatusVault                = "app.gitstatus.vault"                 // Path to vault root
	KeyAppGitstatusJson                 = "app.gitstatus.json"                  // Output in JSON format
	KeyAppIndexVault                    = "app.index.vault"                     // Path to the vault root directory
	KeyAppIndexJson                     = "app.index.json"                      // Output in JSON format
	KeyAppIndexFull                     = "app.index.full"                      // Force full rebuild instead of incremental index
	KeyAppLinksVault                    = "app.links.vault"                     // Path to vault root
	KeyAppLinksJson                     = "app.links.json"                      // Output in JSON format
	KeyAppLinksEdgeType                 = "app.links.edge_type"                 // Filter by edge type
	KeyAppNoteVault                     = "app.note.vault"                      // Path to vault root
	KeyAppNoteJson                      = "app.note.json"                       // Output in JSON format
	KeyAppNoteFrontmatterOnly           = "app.note.frontmatter_only"           // Omit body, headings, blocks
	KeyAppPingOutputMessage             = "app.ping.output_message"             // Default message to display for the ping command
	KeyAppPingOutputColor               = "app.ping.output_color"               // Text color for ping command output (white, red, green, blue, cyan, yellow, ma...
	KeyAppPingUi                        = "app.ping.ui"                         // Enable interactive UI for the ping command
	KeyAppResolveVault                  = "app.resolve.vault"                   // Path to the vault root directory
	KeyAppResolveJson                   = "app.resolve.json"                    // Output in JSON format
	KeyAppSchemaVault                   = "app.schema.vault"                    // Path to vault root
	KeyAppSchemaJson                    = "app.schema.json"                     // Output in JSON format
	KeyAppSearchVault                   = "app.search.vault"                    // Path to vault root
	KeyAppSearchJson                    = "app.search.json"                     // Output in JSON format
	KeyAppSearchLimit                   = "app.search.limit"                    // Maximum results to return
	KeyAppSearchOffset                  = "app.search.offset"                   // Skip first N results
	KeyAppSearchType                    = "app.search.type"                     // Filter by note type
	KeyAppSearchTag                     = "app.search.tag"                      // Filter by tag
	KeyAppVaultstatusVault              = "app.vaultstatus.vault"               // Path to vault root
	KeyAppVaultstatusJson               = "app.vaultstatus.json"                // Output in JSON format
)
