// Package onboard provides the embedded agent-onboarding script as a
// CLI-accessible asset. The canonical doc lives in this package
// (AGENT_ONBOARDING.md) and is embedded in the binary at build time;
// `vaultmind init --print-instructions` prints it on demand. Embedding
// rather than reading from disk means the doc travels with the binary
// — a new user with `go install`'d vaultmind can read the script
// without needing to clone the source repo.
//
// Source-of-truth lives here, not under docs/, because Go's embed
// directive cannot traverse parent directories. README links to this
// path as the human-discoverable copy; the binary embeds the same
// file, so there is one source of truth (manifesto principle 7).
package onboard

import (
	_ "embed"
	"fmt"
	"io"
)

//go:embed AGENT_ONBOARDING.md
var instructions []byte

//go:embed QUICKSTART.md
var quickstart []byte

// commandsRef is the generated grouped command reference (COMMANDS.md). It
// lives inside this package because go:embed cannot traverse parent
// directories; it is regenerated by `vaultmind docs commands --output
// internal/onboard/COMMANDS.md` and a drift test asserts the committed copy
// matches the live catalog (so a new command can't ship un-regenerated).
//
//go:embed COMMANDS.md
var commandsRef []byte

// Instructions returns the embedded agent-onboarding doc as raw
// bytes. Returns the backing slice directly — callers must not mutate
// the returned bytes. A defensive copy would be wasteful for a 25KB
// doc; the only callers today are tests that immediately convert to
// string. Production callers should prefer PrintInstructions.
func Instructions() []byte {
	return instructions
}

// PrintInstructions writes the embedded onboarding doc verbatim to
// the supplied writer. Used by `vaultmind init --print-instructions --full`
// to route output to stdout (or a test buffer). Returns the writer's
// error if any; the embed itself cannot fail at runtime.
func PrintInstructions(w io.Writer) error {
	if _, err := w.Write(instructions); err != nil {
		return fmt.Errorf("writing onboarding instructions: %w", err)
	}
	return nil
}

// Commands returns the embedded grouped command reference (COMMANDS.md) as raw
// bytes. Same no-mutate contract as Instructions. Production callers should
// prefer PrintFull, which appends it to the onboarding guide.
func Commands() []byte {
	return commandsRef
}

// PrintFull writes the full agent-onboarding guide followed by the generated
// grouped command reference, so `vaultmind init --print-instructions --full`
// hands an agent both the wiring narrative AND the complete catalog of
// commands (with when-to-use) in one paste. A blank line separates the two so
// the appended reference reads as its own section.
func PrintFull(w io.Writer) error {
	if _, err := w.Write(instructions); err != nil {
		return fmt.Errorf("writing onboarding instructions: %w", err)
	}
	if _, err := io.WriteString(w, "\n"); err != nil {
		return fmt.Errorf("writing onboarding separator: %w", err)
	}
	if _, err := w.Write(commandsRef); err != nil {
		return fmt.Errorf("writing command reference: %w", err)
	}
	return nil
}

// QuickStart returns the embedded concise quick-start as raw bytes.
// Same no-mutate contract as Instructions: the quick-start is the
// skimmable 20% that gets an agent wired; the full guide is behind
// `--full`. Production callers should prefer PrintQuickStart.
func QuickStart() []byte {
	return quickstart
}

// PrintQuickStart writes the embedded quick-start verbatim to the
// supplied writer. Used by `vaultmind init --print-instructions` (the
// default — quick-start over the full guide). Returns the writer's
// error if any; the embed itself cannot fail at runtime.
func PrintQuickStart(w io.Writer) error {
	if _, err := w.Write(quickstart); err != nil {
		return fmt.Errorf("writing onboarding quick-start: %w", err)
	}
	return nil
}
