#!/usr/bin/env bash
# Scan SBOM for vulnerabilities using Grype
# Works with SBOMs generated by syft (task generate:sbom)
set -eo pipefail

# Source standard output functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/check-output.sh
source "${SCRIPT_DIR}/lib/check-output.sh"

# Severity threshold: critical, high, medium, low, negligible
SEVERITY="${GRYPE_SEVERITY:-high}"

# Allow skipping
if [[ "${SKIP_SBOM_VULN:-}" == "1" ]]; then
    echo "  Skipping SBOM vulnerability scan (SKIP_SBOM_VULN=1)"
    exit 0
fi

# Check for grype installation
if ! command -v grype &> /dev/null; then
    echo "Error: grype is not installed"
    echo ""
    echo "Install with:"
    echo "  brew install grype                       # macOS"
    echo "  curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin"
    echo ""
    echo "Or run: task setup  # Installs all dev tools"
    exit 1
fi

check_header "Scanning SBOM for vulnerabilities"

# Find the latest SBOM file
SBOM_DIR="reports/sbom"
if [[ ! -d "$SBOM_DIR" ]]; then
    echo "  No SBOM directory found. Generating SBOM first..."
    if ! "${SCRIPT_DIR}/generate-sbom.sh" all >/dev/null 2>&1; then
        check_failure \
            "Failed to generate SBOM" \
            "Could not generate SBOM for scanning" \
            "Run: task generate:sbom"
        exit 1
    fi
fi

# Find the latest CycloneDX JSON (preferred by grype)
SBOM_FILE=$(ls -t "$SBOM_DIR"/*.cdx.json 2>/dev/null | head -1)

if [[ -z "$SBOM_FILE" ]]; then
    echo "  No CycloneDX SBOM found. Generating..."
    if ! "${SCRIPT_DIR}/generate-sbom.sh" cyclonedx >/dev/null 2>&1; then
        check_failure \
            "Failed to generate SBOM" \
            "Could not generate CycloneDX SBOM" \
            "Run: task generate:sbom:cyclonedx"
        exit 1
    fi
    SBOM_FILE=$(ls -t "$SBOM_DIR"/*.cdx.json 2>/dev/null | head -1)
fi

echo "  SBOM: $(basename "$SBOM_FILE")"
echo "  Severity threshold: $SEVERITY"
echo ""

# Run grype scan
# --fail-on: exit 1 if vulnerabilities at or above this severity
# --only-fixed: only show vulnerabilities with available fixes
if ! run_check "grype sbom:${SBOM_FILE} --fail-on ${SEVERITY} 2>&1"; then
    # Check if there are actual vulnerabilities vs other errors
    if echo "$CHECK_OUTPUT" | grep -qE "^\s*(Critical|High|Medium|Low)\s+[0-9]+"; then
        # Count vulnerabilities by severity
        CRITICAL=$(echo "$CHECK_OUTPUT" | grep -c "Critical" || echo "0")
        HIGH=$(echo "$CHECK_OUTPUT" | grep -c "High" || echo "0")
        MEDIUM=$(echo "$CHECK_OUTPUT" | grep -c "Medium" || echo "0")
        LOW=$(echo "$CHECK_OUTPUT" | grep -c "Low" || echo "0")

        check_failure \
            "Vulnerabilities found (Critical:$CRITICAL High:$HIGH Medium:$MEDIUM Low:$LOW)" \
            "$CHECK_OUTPUT" \
            "Update vulnerable dependencies:"$'\n'"  go get -u <package>@latest"$'\n'"  go mod tidy"$'\n'"Or set GRYPE_SEVERITY=critical to only fail on critical"
        exit 1
    else
        # Some other error (network, database, etc.)
        check_failure \
            "Grype scan failed" \
            "$CHECK_OUTPUT" \
            "Check network connection and try: grype db update"
        exit 1
    fi
fi

# Get summary even on success
VULN_COUNT=$(echo "$CHECK_OUTPUT" | grep -cE "Critical|High|Medium|Low" 2>/dev/null || true)
VULN_COUNT=${VULN_COUNT:-0}
if [[ "$VULN_COUNT" =~ ^[0-9]+$ ]] && [[ "$VULN_COUNT" -gt 0 ]]; then
    check_success "No vulnerabilities at or above '$SEVERITY' severity ($VULN_COUNT lower-severity found)"
else
    check_success "No vulnerabilities found"
fi
