#!/bin/bash
# validate-task-naming.sh
#
# Validates that all tasks in Taskfile.yml follow ADR-000 naming convention.
# This ensures consistency and prevents naming drift.
#
# ADR-000 Pattern: action:target[:subvariant]
# Valid actions: check, validate, test, generate, build, clean, format, bench
# Allowed standalone: setup, init, install, run, tidy, default, doctor, format, test, build, check, bench, clean

set -e

# Source standard output functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/check-output.sh
source "${SCRIPT_DIR}/lib/check-output.sh"

ERRORS=0
WARNINGS=0
ERROR_DETAILS=""

check_header "Validating ADR-000: Task naming convention"

# Valid actions from ADR-000
VALID_ACTIONS=(check validate test generate build clean format bench setup)

# Allowed standalone tasks (tasks without colons that don't need action:target pattern)
# These are utility/orchestrator tasks that operate on "everything"
ALLOWED_STANDALONE=(
    setup           # Setup development environment
    init            # Initialize new project from scaffold
    install         # Install the binary
    run             # Run the application
    tidy            # Tidy dependencies (go mod tidy)
    default         # Default task (usually points to another task)
    doctor          # Diagnose environment issues
    format          # Format everything
    test            # Test everything
    build           # Build everything
    check           # Check everything (orchestrator)
    bench           # Benchmark everything
    clean           # Clean everything
    lint            # Lint everything
    ckeletin        # Framework include namespace (auto-generated by Task includes)
    ckeletin-version          # Framework version alias (ckeletin: prefix reserved for includes)
    ckeletin-health           # Framework health check alias (ckeletin: prefix reserved for includes)
    ckeletin-update-dry-run   # Framework update dry-run alias (ckeletin: prefix reserved for includes)
    ckeletin-update-check     # Framework compatibility check alias (ckeletin: prefix reserved for includes)
    conform                   # Generate CKSPEC conformance report
)

# Allowed action prefixes beyond the standard ADR-000 actions
# These are for special namespacing cases like framework includes
ALLOWED_ACTIONS_EXTENDED=(
    ckeletin        # Framework tasks (ckeletin:update, etc.)
)

# Function to suggest similar action based on simple heuristics
suggest_similar_action() {
    local invalid=$1
    shift
    local valid_actions=("$@")

    local first_char="${invalid:0:1}"
    local len=${#invalid}

    # Try to find action with same starting letter and similar length
    for action in "${valid_actions[@]}"; do
        if [[ "$action" == "$first_char"* ]]; then
            local action_len=${#action}
            local diff=$((len - action_len))
            # Absolute value
            diff=${diff#-}

            # If within 2 characters difference, suggest it
            if [ $diff -le 2 ]; then
                echo "$action"
                return
            fi
        fi
    done

    # No similar found, return empty
    echo ""
}

# Function to find similar tasks containing the invalid task name
suggest_fix_for_task() {
    local invalid_task=$1
    local all_tasks=$2

    # Strategy 1: Find tasks containing this word (case-insensitive)
    local similar=$(echo "$all_tasks" | grep -i ":$invalid_task" | head -3)

    if [ -z "$similar" ]; then
        # Also try finding tasks where the word appears anywhere
        similar=$(echo "$all_tasks" | grep -i "$invalid_task" | head -3)
    fi

    if [ -n "$similar" ]; then
        echo "   💡 Found similar tasks:"
        echo "$similar" | while IFS= read -r task; do
            echo "      • $task"
        done

        # Extract the most likely intended pattern (first match)
        local first_match=$(echo "$similar" | head -1)

        # If it's a compound task, suggest using that pattern
        if [[ "$first_match" =~ : ]]; then
            local action=$(echo "$first_match" | cut -d: -f1)
            echo "   💡 Suggested fix: Use pattern '$action:$invalid_task'"
        fi
    else
        # No similar tasks found, suggest common patterns
        echo "   💡 Try one of these patterns:"
        echo "      • test:$invalid_task     (for testing variants)"
        echo "      • check:$invalid_task    (for validation checks)"
        echo "      • generate:$invalid_task (for code generation)"
    fi
}

# Extract task names from Taskfile.yml
# Match lines like "  taskname:" or "  action:target:" at start of line
# Only remove the TRAILING colon and leading spaces
TASK_NAMES=$(grep "^  [a-z][a-z0-9:_-]*:$" Taskfile.yml | sed 's/:$//' | sed 's/^  //' | sort)

if [ -z "$TASK_NAMES" ]; then
    check_failure "No tasks found in Taskfile.yml" "" "Is Taskfile.yml present and valid?"
    exit 1
fi

for task in $TASK_NAMES; do
    # Skip if task is in allowed standalone list
    if [[ " ${ALLOWED_STANDALONE[*]} " =~ " ${task} " ]]; then
        continue
    fi

    # Check if task has a colon (is a compound task)
    if [[ "$task" =~ : ]]; then
        # Extract action (first part before colon)
        action=$(echo "$task" | cut -d: -f1)

        # Validate action is in VALID_ACTIONS or ALLOWED_ACTIONS_EXTENDED list
        if [[ ! " ${VALID_ACTIONS[*]} " =~ " ${action} " ]] && [[ ! " ${ALLOWED_ACTIONS_EXTENDED[*]} " =~ " ${action} " ]]; then
            ERROR_DETAILS+="❌ Task '$task': Invalid action '$action'"$'\n'
            ERROR_DETAILS+="   Valid actions: ${VALID_ACTIONS[*]}"$'\n'

            # Suggest similar action
            suggestion=$(suggest_similar_action "$action" "${VALID_ACTIONS[@]}")
            if [ -n "$suggestion" ]; then
                ERROR_DETAILS+="   💡 Did you mean '$suggestion:${task#*:}'?"$'\n'
            fi

            ERROR_DETAILS+=$'\n'
            ((++ERRORS))
        fi
    else
        # Standalone task not in allowed list
        ERROR_DETAILS+="❌ Task '$task': Standalone task not in allowed list"$'\n'
        ERROR_DETAILS+="   Allowed standalone tasks: ${ALLOWED_STANDALONE[*]}"$'\n'

        # Generate smart suggestions
        suggestions=$(suggest_fix_for_task "$task" "$TASK_NAMES")
        ERROR_DETAILS+="$suggestions"$'\n'
        ERROR_DETAILS+=$'\n'

        ((++ERRORS))
    fi
done

# Summary
if [ $ERRORS -eq 0 ] && [ $WARNINGS -eq 0 ]; then
    check_success "All tasks follow ADR-000 naming convention"
    exit 0
elif [ $ERRORS -eq 0 ]; then
    check_success "All tasks pass (${WARNINGS} warning(s))"
    exit 0
else
    check_failure \
        "${ERRORS} task naming violation(s) found" \
        "$ERROR_DETAILS" \
        "See docs/adr/000-task-based-single-source-of-truth.md for naming guidelines"
    exit 1
fi
