package baseline_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/peiman/vaultmind/internal/baseline"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// LoadQueries parses the golden-query YAML fixture. The shape is kept
// deliberately minimal (name/text/expected) so edits stay readable and
// diff-friendly. Changing this shape breaks every committed fixture at
// once, so the type stays stable by convention.
func TestLoadQueries_RoundTripsYAMLFixture(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "queries.yaml")
	require.NoError(t, os.WriteFile(path, []byte(`
- name: spreading
  text: spreading activation
  expected: [c-spreading]
- name: rrf
  text: reciprocal rank
  expected: [c-rrf, c-hybrid]
`), 0o644))

	queries, err := baseline.LoadQueries(path)
	require.NoError(t, err)
	require.Len(t, queries, 2)
	assert.Equal(t, "spreading", queries[0].Name)
	assert.Equal(t, "spreading activation", queries[0].Text)
	assert.Equal(t, []string{"c-spreading"}, queries[0].Expected)
	assert.Equal(t, []string{"c-rrf", "c-hybrid"}, queries[1].Expected)
}

func TestLoadQueries_MissingFileErrors(t *testing.T) {
	_, err := baseline.LoadQueries("/does/not/exist.yaml")
	require.Error(t, err)
}

// LoadSnapshot reads the committed baseline.json produced by a previous
// run. The shape matches Report's JSON tags exactly so snapshot files
// generated by the runner round-trip through Go decode without mapping.
func TestLoadSnapshot_RoundTripsJSONReport(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "baseline.json")
	require.NoError(t, os.WriteFile(path, []byte(`{
  "k": 5,
  "queries": [
    {"name": "spreading", "text": "spreading activation",
     "expected": ["c-spreading"], "result_ids": ["c-spreading"],
     "hit_at_k": 1.0, "reciprocal_rank": 1.0}
  ],
  "hit_at_k": 1.0,
  "mrr": 1.0
}`), 0o644))

	snap, err := baseline.LoadSnapshot(path)
	require.NoError(t, err)
	assert.Equal(t, 5, snap.K)
	assert.Equal(t, 1.0, snap.HitAtK)
	assert.Equal(t, 1.0, snap.MRR)
	require.Len(t, snap.Queries, 1)
	assert.Equal(t, "spreading", snap.Queries[0].Name)
}

// CompareToSnapshot is the regression gate: current run vs. committed
// snapshot. Any aggregate drop beyond tolerance is a failure. Same-or-
// better is always OK; IMPROVEMENTS don't fail so we can refresh the
// snapshot deliberately instead of every good-luck run tripping CI.
func TestCompareToSnapshot_IdenticalReportsPass(t *testing.T) {
	snap := &baseline.Report{K: 5, HitAtK: 0.8, MRR: 0.6, Queries: []baseline.QueryResult{
		{Name: "a", HitAtK: 1.0, ReciprocalRank: 1.0},
	}}
	current := &baseline.Report{K: 5, HitAtK: 0.8, MRR: 0.6, Queries: []baseline.QueryResult{
		{Name: "a", HitAtK: 1.0, ReciprocalRank: 1.0},
	}}
	diff, err := baseline.CompareToSnapshot(current, snap, baseline.DefaultTolerance)
	require.NoError(t, err)
	assert.True(t, diff.OK, "identical reports must pass")
	assert.Empty(t, diff.Regressions)
}

// A current run that matches the snapshot on aggregates but IMPROVES on
// a per-query basis is still OK — the gate is "no regression", not "no
// change". Regressions are the actionable signal.
func TestCompareToSnapshot_ImprovementsAreOK(t *testing.T) {
	snap := &baseline.Report{K: 5, HitAtK: 0.5, MRR: 0.3}
	current := &baseline.Report{K: 5, HitAtK: 0.9, MRR: 0.8}
	diff, err := baseline.CompareToSnapshot(current, snap, baseline.DefaultTolerance)
	require.NoError(t, err)
	assert.True(t, diff.OK, "improvement must pass")
	assert.Empty(t, diff.Regressions)
}

// A drop in aggregate Hit@K beyond tolerance fails the gate AND names
// which metric dropped + by how much. Regression without provenance is
// what we're specifically building this gate to avoid.
func TestCompareToSnapshot_HitAtKRegressionFails(t *testing.T) {
	snap := &baseline.Report{K: 5, HitAtK: 0.9, MRR: 0.8}
	current := &baseline.Report{K: 5, HitAtK: 0.6, MRR: 0.8} // Hit@K dropped 0.3
	diff, err := baseline.CompareToSnapshot(current, snap, 0.05)
	require.NoError(t, err)
	assert.False(t, diff.OK, "0.3 drop at 0.05 tolerance must fail")
	require.NotEmpty(t, diff.Regressions)
	// Regression description should include the metric name + magnitude
	// so the operator can act without re-reading the code.
	joined := ""
	for _, r := range diff.Regressions {
		joined += r + "\n"
	}
	assert.Contains(t, joined, "hit_at_k")
	assert.Contains(t, joined, "0.9")
	assert.Contains(t, joined, "0.6")
}

// A per-query hit_at_k regression surfaces even if the aggregate stayed
// the same (one query improved, another regressed, mean unchanged).
// Aggregate-only comparison would hide the 'mask' problem.
func TestCompareToSnapshot_PerQueryRegressionFails(t *testing.T) {
	snap := &baseline.Report{K: 5, HitAtK: 0.5, MRR: 0.5, Queries: []baseline.QueryResult{
		{Name: "a", HitAtK: 1.0, ReciprocalRank: 1.0},
		{Name: "b", HitAtK: 0.0, ReciprocalRank: 0.0},
	}}
	current := &baseline.Report{K: 5, HitAtK: 0.5, MRR: 0.5, Queries: []baseline.QueryResult{
		{Name: "a", HitAtK: 0.0, ReciprocalRank: 0.0}, // regressed
		{Name: "b", HitAtK: 1.0, ReciprocalRank: 1.0}, // improved
	}}
	diff, err := baseline.CompareToSnapshot(current, snap, 0.05)
	require.NoError(t, err)
	assert.False(t, diff.OK, "per-query regression must surface even when aggregate is unchanged")
	joined := ""
	for _, r := range diff.Regressions {
		joined += r + "\n"
	}
	assert.Contains(t, joined, "a", "regression description must name the specific query")
}

// An MRR regression beyond tolerance fails even when Hit@K held steady.
// Hit@K is binary-per-query; MRR is rank-sensitive and can catch
// reordering that Hit@K ignores (e.g., top-1 became top-5).
func TestCompareToSnapshot_MRRRegressionFails(t *testing.T) {
	snap := &baseline.Report{K: 5, HitAtK: 1.0, MRR: 0.9}
	current := &baseline.Report{K: 5, HitAtK: 1.0, MRR: 0.4} // rank drift
	diff, err := baseline.CompareToSnapshot(current, snap, 0.05)
	require.NoError(t, err)
	assert.False(t, diff.OK)
	joined := ""
	for _, r := range diff.Regressions {
		joined += r + "\n"
	}
	assert.Contains(t, joined, "mrr")
}

// K mismatch between snapshot and current run is an operator error, not
// a silent comparison — comparing Hit@5 to Hit@10 numbers would produce
// nonsense.
func TestCompareToSnapshot_KMismatchErrors(t *testing.T) {
	snap := &baseline.Report{K: 5, HitAtK: 1.0}
	current := &baseline.Report{K: 10, HitAtK: 1.0}
	_, err := baseline.CompareToSnapshot(current, snap, 0.05)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "k")
}
